version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore"
      include: scope
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Padzx"
    reviewers: []

  - package-ecosystem: "gradle"
    directory: "/log-ingestion"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore"
      include: scope
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Padzx"
    reviewers: []

  - package-ecosystem: "gradle"
    directory: "/log-processor"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore"
      include: scope
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Padzx"
    reviewers: []

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
      timezone: "Etc/UTC"
    labels:
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Etc/UTC"
    labels:
      - "workflow"
      - "dependencies"
