global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/kafka_alerts.yml"
  - "/etc/prometheus/rules/zookeeper_alerts.yml"

scrape_configs:
  # Scrape Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7072']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Scrape Zookeeper metrics
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:7000']
    metrics_path: '/metrics'
    scrape_interval: 15s
