name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
      - feature/**
  pull_request:
    branches:
      - develop
      - main
      - feature/**

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      java-home: ${{ steps.set-up-jdk.outputs.java-home }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        id: set-up-jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java Installation
        run: |
          java -version
          echo "JAVA_HOME is set to: $JAVA_HOME"
      - name: Cache Gradle dependencies
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  log-ingestion:
    needs: setup
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'log-ingestion') || github.ref == 'refs/heads/feature/log-ingestion-microservice'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17 for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java Installation
        run: |
          java -version
          echo "JAVA_HOME is set to: $JAVA_HOME"
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Project - Log Ingestion
        run: ./gradlew :log-ingestion:clean :log-ingestion:build --warning-mode all
        env:
          JAVA_HOME: ${{ needs.setup.outputs.java-home }}

      - name: Run Unit Tests - Log Ingestion
        run: ./gradlew :log-ingestion:unitTest --warning-mode all
        env:
          JAVA_HOME: ${{ needs.setup.outputs.java-home }}
      - name: Publish Test Results - Log Ingestion
        uses: actions/upload-artifact@v3
        with:
          name: Log Ingestion Test Results
          path: '**/log-ingestion/build/test-results/**/*.xml'

  log-processor:
    needs: setup
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'log-processor') || github.ref == 'refs/heads/feature/log-processor-microservice'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17 for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java Installation
        run: |
          java -version
          echo "JAVA_HOME is set to: $JAVA_HOME"
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Project - Log Processor
        run: ./gradlew :log-processor:test --warning-mode all -Dspring.profiles.active=test
        env:
          JAVA_HOME: ${{ needs.setup.outputs.java-home }}
          SPRING_PROFILES_ACTIVE: test

      - name: Run Unit Tests - Log Processor
        run: ./gradlew :log-processor:unitTest --warning-mode all
        env:
          JAVA_HOME: ${{ needs.setup.outputs.java-home }}

      - name: Publish Test Results - Log Processor
        uses: actions/upload-artifact@v3
        with:
          name: Log Processor Test Results
          path: '**/log-processor/build/test-results/**/*.xml'